DROP DATABASE IF EXISTS AGENDAR;
CREATE DATABASE AGENDAR;
USE AGENDAR;

-- CRIAÇÃO DE TABELAS

DROP TABLE IF EXISTS COMERCIO;
CREATE TABLE COMERCIO (
  ID_COMERCIO INT PRIMARY KEY AUTO_INCREMENT,
  CNPJ_COMERCIO CHAR (14) UNIQUE, 
  NOME_COMERCIO VARCHAR (75) NOT NULL,
  TEL_COMERCIO CHAR (11) NOT NULL UNIQUE,
  SENHA_COMERCIO CHAR (64) NOT NULL,
  ULTIMA_DATA_DOACAO DATE,
  SECRET_COMERCIO VARCHAR(172) NOT NULL
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  ID_USER INT AUTO_INCREMENT PRIMARY KEY,
  NOME_USER VARCHAR (75),
  TEL_USER CHAR (11) NOT NULL UNIQUE,
  EMAIL_USER VARCHAR (150) UNIQUE,
  CANCELAMENTOS INT DEFAULT 0 NOT NULL,
  SENHA_USER CHAR (64) NOT NULL,
  SECRET_USER VARCHAR(44) NOT NULL
);

DROP TABLE IF EXISTS AGENDAMENTO;
CREATE TABLE AGENDAMENTO (
  ID_AGENDAMENTO INT AUTO_INCREMENT,
  ID_USER INT NOT NULL,
  DATA_CRIACAO_AGENDAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_AGENDAMENTO DATE,
  HORARIO_AGENDAMENTO TIME,
  PRIMARY KEY (ID_AGENDAMENTO),
  FOREIGN KEY (ID_USER) REFERENCES USER (ID_USER)
);

DROP TABLE IF EXISTS RESTRICAO;
CREATE TABLE RESTRICAO (
  ID_RESTRICAO INT AUTO_INCREMENT PRIMARY KEY,
  DIA_SEMANA INT,
  HORARIO_INICIO TIME,
  HORARIO_FIM TIME,
  DATA_INICIO DATE,
  DATA_FIM DATE
);

DROP TABLE IF EXISTS DATAS_ESPECIAIS;
CREATE TABLE DATAS_ESPECIAIS (
  ID_DATA INT AUTO_INCREMENT PRIMARY KEY,
  DATA_ESPECIAL DATE,
  HORARIO_ESPECIAL TIME
);

DROP TABLE IF EXISTS SERVICOS;
CREATE TABLE SERVICOS (
  ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
  NOME_SERVICO VARCHAR(75) NOT NULL,
  PRECO_SERVICO DECIMAL(11,2) DEFAULT 0
);

DROP TABLE IF EXISTS SERVICOS_AGENDAMENTO;
CREATE TABLE SERVICOS_AGENDAMENTO (
  ID_SERVICO INT NOT NULL,
  ID_AGENDAMENTO INT NOT NULL,
  FOREIGN KEY (ID_SERVICO) REFERENCES SERVICOS(ID_SERVICO),
  FOREIGN KEY (ID_AGENDAMENTO) REFERENCES AGENDAMENTO(ID_AGENDAMENTO)
);

-- CRIAÇÃO DE VIEWS

DROP VIEW IF EXISTS AGENDAMENTOS_SEUS_SERVICOS;
CREATE VIEW AGENDAMENTOS_SEUS_SERVICOS AS
SELECT AGENDAMENTO.ID_AGENDAMENTO, HORARIO_AGENDAMENTO, DATA_AGENDAMENTO, ID_USER, SERVICOS.ID_SERVICO, NOME_SERVICO, PRECO_SERVICO FROM AGENDAMENTO
INNER JOIN SERVICOS_AGENDAMENTO
ON SERVICOS_AGENDAMENTO.ID_AGENDAMENTO = AGENDAMENTO.ID_AGENDAMENTO
INNER JOIN SERVICOS
ON SERVICOS.ID_SERVICO = SERVICOS_AGENDAMENTO.ID_SERVICO;

DROP VIEW IF EXISTS RELATORIO_SERVICOS;
CREATE VIEW RELATORIO_SERVICOS AS
SELECT NOME_SERVICO, (
  SELECT COUNT(*)  FROM  SERVICOS_AGENDAMENTO
  WHERE SERVICOS.ID_SERVICO = SERVICOS_AGENDAMENTO.ID_SERVICO
) AS QUANTIDADE FROM SERVICOS;


DROP VIEW IF EXISTS RELATORIO_CANCELAMENTOS_AGENDAMENTOS;
CREATE VIEW RELATORIO_CANCELAMENTOS_AGENDAMENTOS AS
SELECT (SELECT COALESCE(SUM(CANCELAMENTOS), 0) FROM USER)  AS CANCELAMENTOS,
(SELECT COUNT(ID_AGENDAMENTO)
FROM AGENDAMENTO
INNER JOIN USER
ON AGENDAMENTO.ID_USER = USER.ID_USER
WHERE (DATA_AGENDAMENTO < CURDATE()
  OR ( DATA_AGENDAMENTO = CURDATE() AND HORARIO_AGENDAMENTO <= CURTIME()))) AS AGENDAMENTOS;


DROP VIEW IF EXISTS RELATORIO_MENSAL;
CREATE VIEW RELATORIO_MENSAL AS
SELECT DATE_FORMAT(DATA_AGENDAMENTO, "%m/%Y")  AS MES, SUM(PRECO_SERVICO) AS TOTAL FROM AGENDAMENTOS_SEUS_SERVICOS;
WHERE (DATA_AGENDAMENTO < CURDATE()
  OR ( DATA_AGENDAMENTO = CURDATE() AND HORARIO_AGENDAMENTO <= CURTIME()))
GROUP BY DATE_FORMAT(DATA_AGENDAMENTO, "%m/%Y")
ORDER BY DATE_FORMAT(DATA_AGENDAMENTO, "%m/%Y") DESC
LIMIT 7;


DROP VIEW IF EXISTS RELATORIO_MES;
CREATE VIEW RELATORIO_MES AS
SELECT DATE_FORMAT(DATA_AGENDAMENTO, '%d') AS DIA, SUM(PRECO_SERVICO) AS TOTAL FROM AGENDAMENTOS_SEUS_SERVICOS
WHERE DATE_FORMAT(DATA_AGENDAMENTO, '%m%Y') = DATE_FORMAT(CURDATE(), '%m%Y')
  AND ((DATA_AGENDAMENTO < CURDATE()
  OR ( DATA_AGENDAMENTO = CURDATE() AND HORARIO_AGENDAMENTO <= CURTIME())))
GROUP BY DATE_FORMAT(DATA_AGENDAMENTO, '%d')
ORDER BY DATE_FORMAT(DATA_AGENDAMENTO, '%d');

-- INSERTS

INSERT INTO COMERCIO (ID_COMERCIO, CNPJ_COMERCIO, NOME_COMERCIO, TEL_COMERCIO, SENHA_COMERCIO, SECRET_COMERCIO) VALUES(0, '00000000000000', 'Barbearia', '15999999999', '$2y$10$kaM78CwiZ5PS.0e3PA/EKOyApQ/Xh807NREv2M09Cp4Hg8quU.mlm', 'A7TfKS2X+GABSIP3ySxgR1xtH+VKJ9wcfcWPzoifT7iMI5K9LoloA+oCNC4XlEibGWGoICSMHQjU5UUCSVCGrhgx2+4Mu8qmPZGBKjzMMNWW6NLS8gYR4QgVh0M4pzfrXHrhjaFwl1/Fs959FG1KGR3nHbtNDoM3gPMgERIfYgk=');

INSERT INTO AGENDAMENTO (ID_USER, DATA_AGENDAMENTO) VALUES (1, '2023-08-21');
INSERT INTO SERVICOS_AGENDAMENTO VALUES (2, 16);