CREATE DATABASE AGENDAR;
USE AGENDAR;

DROP TABLE IF EXISTS COMERCIO;
CREATE TABLE COMERCIO (
  ID_COMERCIO INT PRIMARY KEY,
  CNPJ CHAR (14) UNIQUE, 
  NOME_COMERCIO VARCHAR (75) NOT NULL,
  TEL_COMERCIO CHAR (11) NOT NULL UNIQUE,
  SENHA_COMERCIO CHAR (64) NOT NULL,
  ULTIMA_DATA_DOACAO DATE,
  SECRET_COMERCIO VARCHAR(44) NOT NULL
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  ID_USER INT AUTO_INCREMENT PRIMARY KEY,
  NOME_USER VARCHAR (75),
  TEL_USER CHAR (11) NOT NULL UNIQUE,
  EMAIL_USER VARCHAR (150) UNIQUE,
  SENHA_USER CHAR (64) NOT NULL,
  SECRET_USER VARCHAR(44) NOT NULL
);

DROP TABLE IF EXISTS AGENDAMENTO;
CREATE TABLE AGENDAMENTO (
  ID_AGENDAMENTO INT AUTO_INCREMENT PRIMARY KEY,
  ID_USER INT NOT NULL REFERENCES USER (ID_USER),
  DATA_CRIACAO_AGENDAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_AGENDAMENTO DATE,
  HORARIO_AGENDAMENTO TIME
);

DROP TABLE IF EXISTS RESTRICAO;
CREATE TABLE RESTRICAO (
  ID_RESTRICAO INT AUTO_INCREMENT PRIMARY KEY,
  DIA_SEMANA INT,
  HORARIO_INICIO TIME DEFAULT '00:00',
  HORARIO_FIM TIME DEFAULT '23:59',
  DATA_INICIO DATE,
  DATA_FIM DATE
);

DROP TABLE IF EXISTS DATAS_ESPECIAIS;
CREATE TABLE DATAS_ESPECIAIS (
  ID_DATA INT AUTO_INCREMENT PRIMARY KEY,
  DATA_ESPECIAL DATE,
  HORARIO_ESPECIAL TIME
);

DROP TABLE IF EXISTS SERVICOS;
CREATE TABLE SERVICOS (
  ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
  NOME_SERVICO VARCHAR(75) NOT NULL,
  PRECO_SERVICO DECIMAL(11,2) DEFAULT 0
);

DROP TABLE IF EXISTS SERVICOS_AGENDAMENTO;
CREATE TABLE SERVICOS_AGENDAMENTO (
  ID_SERVICO INT NOT NULL REFERENCES SERVICO(ID_SERVICO),
  ID_AGENDAMENTO INT NOT NULL REFERENCES AGENDAMENTO(ID_AGENDAMENTO)
);

INSERT INTO COMERCIO (CNPJ_COMERCIO, NOME_COMERCIO, TEL_COMERCIO, SENHA_COMERCIO, SECRET_COMERCIO) VALUES('00000000000000', 'Barbearia', '15999999999', '$2y$10$kaM78CwiZ5PS.0e3PA/EKOyApQ/Xh807NREv2M09Cp4Hg8quU.mlm', 'A7TfKS2X+GABSIP3ySxgR1xtH+VKJ9wcfcWPzoifT7iMI5K9LoloA+oCNC4XlEibGWGoICSMHQjU5UUCSVCGrhgx2+4Mu8qmPZGBKjzMMNWW6NLS8gYR4QgVh0M4pzfrXHrhjaFwl1/Fs959FG1KGR3nHbtNDoM3gPMgERIfYgk=');